services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_0900_ai_ci","--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-uroot","-padmin"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: web
    env_file:
      - .env
    command: ["/bin/bash","-c","chmod +x docker/entrypoint.sh && docker/entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
