apiVersion: v1
kind: ConfigMap
metadata:
  name: chan-config
data:
  DEBUG: "false"
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: chan
  DB_USER: chan
  REDIS_URL: redis://redis:6379/0
  TIME_ZONE: UTC

