# Generated by Django 5.0.7 on 2025-10-07 03:21

import apps.inventory.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.inventory.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.inventory.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lot", models.CharField(max_length=64)),
                ("qty", models.IntegerField()),
                ("available_qty", models.IntegerField()),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.warehouse"
                    ),
                ),
            ],
            options={
                "unique_together": {("sku", "warehouse", "lot")},
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.inventory.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CANCELLED", "CANCELLED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("ttl_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order_ref", models.CharField(blank=True, max_length=64)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.warehouse"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.inventory.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("INBOUND", "INBOUND"),
                            ("RESERVE", "RESERVE"),
                            ("RELEASE", "RELEASE"),
                            ("ALLOCATE", "ALLOCATE"),
                            ("SHIP", "SHIP"),
                            ("ADJUST", "ADJUST"),
                        ],
                        max_length=16,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("ref", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stockbatch",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.sku"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.warehouse"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sku", "warehouse", "created_at"],
                        name="inventory_s_sku_id_046986_idx",
                    )
                ],
            },
        ),
    ]
