# Generated by Django 5.0.7 on 2025-10-07 03:22

import apps.audit.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.audit.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(blank=True, max_length=120)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("request_body", models.TextField(blank=True)),
                ("response_code", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ttl", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
