# Generated by Django 5.2.7 on 2025-10-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_rename_warehouses__warehouse_6a59b1_idx_warehouses__warehou_d82d4c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorybatch',
            new_name='warehouses__warehou_d82d4c_idx',
            old_name='warehouses__warehouse_6a59b1_idx',
        ),
    ]
